name: Gradle CI Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      security-events: write # for CodeQL
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: java
    - name: Build with Gradle
      run: |
        cd $GITHUB_WORKSPACE
        ./gradlew build jacocoTestReport
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
